version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: exprezzzo-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: exprezzzo-db
    environment:
      POSTGRES_DB: exprezzzo
      POSTGRES_USER: exprezzzo
      POSTGRES_PASSWORD: exprezzzo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: exprezzzo-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  ollama_data:
  postgres_data:
  redis_data:
